export const TOOL_TYPE = {
  TEXTBOX: "TEXT_BOX",
  STROKE_PROP_SELECTOR: "STROKE_PROP_SELECTOR",
  OPACITY_SELECTOR: "OPACITY_SELECTOR",
  ERASER: "ERASER",
  SHAPES: "SHAPES",
  UNDO: "UNDO",
  POINTER: "POINTER",
  ADD_IMAGE: "ADD_IMAGE",
  DOWNLOAD_SCREENSHOT: "DOWNLOAD_SCREENSHOT",
};

export const SHAPES = {
  CIRCLE: "CIRCLE",
  SQUARE: "SQUARE",
  RECTANGLE: "RECTANGLE",
  TRIANGLE: "TRIANGLE",
  DIAMOND: "DIAMOND",
  LINE: "LINE",
  ARROW: "ARROW",
  STAR: "STAR",
};

export const MQTT_TOPICS = {
  WHTIEBOARD: "anydone/whiteboard/123",
  CHAT: "treeleaf/chat/demo",
};

export const BACKGROUNDS = {
  WHITE: "WHITE",
  BLACK: "BLACK",
  DOTTED: "DOTTED",
  GRID: "GRID",
};
